services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'

  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=summarizer'
      - 'POSTGRES_PASSWORD=summarizer'
      - 'POSTGRES_USER=summarizer'
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
